// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhDm1t_XuUtK6fMcuvM-Tl94Anun9H00',
    appId: '1:634145425461:web:b4c3cb7f95cc6f1422897c',
    messagingSenderId: '634145425461',
    projectId: 'chat-app-40ca2',
    authDomain: 'chat-app-40ca2.firebaseapp.com',
    storageBucket: 'chat-app-40ca2.appspot.com',
    measurementId: 'G-TBMWVX2E0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz6eKjVGLGEsmFuXH8zHQFIexE7wXbDDI',
    appId: '1:634145425461:android:477adf8b0af8b6b722897c',
    messagingSenderId: '634145425461',
    projectId: 'chat-app-40ca2',
    storageBucket: 'chat-app-40ca2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWSZ-NL3DKxlzmXj8-sIczw88IsKBm1W8',
    appId: '1:634145425461:ios:d5c315f9c0467f9722897c',
    messagingSenderId: '634145425461',
    projectId: 'chat-app-40ca2',
    storageBucket: 'chat-app-40ca2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWSZ-NL3DKxlzmXj8-sIczw88IsKBm1W8',
    appId: '1:634145425461:ios:d5c315f9c0467f9722897c',
    messagingSenderId: '634145425461',
    projectId: 'chat-app-40ca2',
    storageBucket: 'chat-app-40ca2.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVhDm1t_XuUtK6fMcuvM-Tl94Anun9H00',
    appId: '1:634145425461:web:1a81863e2fd9052322897c',
    messagingSenderId: '634145425461',
    projectId: 'chat-app-40ca2',
    authDomain: 'chat-app-40ca2.firebaseapp.com',
    storageBucket: 'chat-app-40ca2.appspot.com',
    measurementId: 'G-6E7CQ417DX',
  );
}
