// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuW1jIWBkNo7XP9DdAVWGYR_nHegXy66c',
    appId: '1:539800302434:web:9920f77e3717842f77f23b',
    messagingSenderId: '539800302434',
    projectId: 'chat-app-ea15b',
    authDomain: 'chat-app-ea15b.firebaseapp.com',
    storageBucket: 'chat-app-ea15b.appspot.com',
    measurementId: 'G-GZY0N9EDS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_PdNLnoMqyYMH8pUige_vfCVPQICiwNs',
    appId: '1:539800302434:android:cc37317b6204cae977f23b',
    messagingSenderId: '539800302434',
    projectId: 'chat-app-ea15b',
    storageBucket: 'chat-app-ea15b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByGaiaHI7g07KKpdtx1uDNjGEvSFevmSk',
    appId: '1:539800302434:ios:f7bfd68c221517ce77f23b',
    messagingSenderId: '539800302434',
    projectId: 'chat-app-ea15b',
    storageBucket: 'chat-app-ea15b.appspot.com',
    iosClientId: '539800302434-jc00vpffqp18arad9tlmid740ujcuaai.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByGaiaHI7g07KKpdtx1uDNjGEvSFevmSk',
    appId: '1:539800302434:ios:f7bfd68c221517ce77f23b',
    messagingSenderId: '539800302434',
    projectId: 'chat-app-ea15b',
    storageBucket: 'chat-app-ea15b.appspot.com',
    iosClientId: '539800302434-jc00vpffqp18arad9tlmid740ujcuaai.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}